name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 14
        
    - name: Install TypeScript and Less
      run: npm i typescript less
      
    - name: Transpile script
      run: npx tsc -t es6 brv.ts
      
    - name: Transpile stylesheet
      run: npx lessc brv.less brv.css

    - name: Build
      run: go build -v
